services:
  psos:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    volumes:
      - psosSrc:/home/javauser/java
    depends_on:
      - db
      - angular
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/user12
      - SPRING_DATASOURCE_USERNAME=user12
      - SPRING_DATASOURCE_PASSWORD=user
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres:14.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=user12
      - POSTGRES_PASSWORD=user
    ports:
      - '5432:5432'

  angular:
    build:
      context: ./
      dockerfile: DockerfileFront
    volumes:
      - psos-angular:/home/angularuser/angular
    ports:
      - '3000:3000'


volumes:
  psosSrc:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/postgresql/

  psos-angular:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/angular/
